######################
# No python Playbook #
######################
---
- name: "Install python"
  hosts: "no_python"
  become: true
  gather_facts: false

  tasks:
  - name: "RAW Python install"
    ansible.builtin.raw: apt update && apt install -y python3-minimal
    args: 
      executable: /bin/bash

  - name: "Install python deps"
    ansible.builtin.apt:
      name:
        - python3-pip
        - python3-setuptools
      state: latest
      update_cache: true
