---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: test-docker-centos-7
    image: docker.io/pycontribs/centos:7
    priveleged: true
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: test-docker-centos-8
    image: docker.io/pycontribs/centos:8
    priveleged: true
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro    
provisioner:
  name: ansible
  lint: 
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
lint: set -e ; yamllint .
