---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: "Example assertion"
    assert:
      that: true
  - name: "nginx - installed"
    ansible.builtin.package:
      name: "nginx"
      state: "present"
  - name: "nginx - start and enabled"
    ansible.builtin.service:
      name: "nginx"
      state: "started"
      enabled: "yes"
